version: "3.5"
services:
  redis:
    image: redis:7
    networks:
      - komunitin  

  notifications:
    depends_on:
      - redis
    build: .
    ports:
     - 2028:2028 
    environment:
      - KOMUNITIN_ACCOUNTING_URL=http://integralces:2029/ces/api/accounting
      - KOMUNITIN_SOCIAL_URL=http://integralces:2029/ces/api/social
      - KOMUNITIN_AUTH_URL=http://integralces:2029/oauth2
      - KOMUNITIN_APP_URL=https://localhost:2030
      - NOTIFICATIONS_CLIENT_ID=notifications-service
      - NOTIFICATIONS_CLIENT_SECRET=komunitin
    volumes:
      - "./komunitin-project-firebase-adminsdk.json:/opt/notifications/komunitin-project-firebase-adminsdk.json"

    profiles:
     - "run"
    
    networks:
     - komunitin
  
  notifications-dev:
    build:
      context: .
      target: notifications-dev 
    ports: 
      - "2028:2028"
      - "40000:40000"
    volumes:
      - .:/opt/notifications
    environment:
      - KOMUNITIN_ACCOUNTING_URL=http://integralces:2029/ces/api/accounting
      - KOMUNITIN_SOCIAL_URL=http://integralces:2029/ces/api/social
      - KOMUNITIN_AUTH_URL=http://integralces:2029/oauth2
      - KOMUNITIN_APP_URL=https://localhost:2030
      - NOTIFICATIONS_CLIENT_ID=notifications-service
      - NOTIFICATIONS_CLIENT_SECRET=komunitin
    profiles:
      - "dev"
    networks:
      - komunitin
      
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
     - REDIS_HOSTS=local:redis:6379
    ports:
     - "2027:8081" 
    profiles:
      - "dev"
    networks:
      - komunitin

networks:
  komunitin:
    driver: bridge
    name: komunitin