services:
  app:
    ports: !reset []
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.app-${COMPOSE_PROJECT_NAME}.rule=Host(`${KOMUNITIN_DOMAIN}`)"
      - "traefik.http.routers.app-${COMPOSE_PROJECT_NAME}.entrypoints=websec"
      - "traefik.http.routers.app-${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.app-${COMPOSE_PROJECT_NAME}.tls.certresolver=myresolver"
    networks:
      - proxy
  
  notifications:
    ports: !reset []
    expose:
      - "2028"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.notifications-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=2028"
      - "traefik.http.routers.notifications-${COMPOSE_PROJECT_NAME}.rule=Host(`notifications.${KOMUNITIN_DOMAIN}`) && PathRegexp(`/{code:[a-zA-Z0-9]+}/events`)"
      - "traefik.http.routers.notifications-${COMPOSE_PROJECT_NAME}.entrypoints=websec"
      - "traefik.http.routers.notifications-${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.notifications-${COMPOSE_PROJECT_NAME}.tls.certresolver=myresolver"
    networks:
      - proxy
  
  notifications-ts:
    ports: !reset []
    expose:
      - "2023"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.notifications-ts-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=2023"
      - "traefik.http.routers.notifications-ts-${COMPOSE_PROJECT_NAME}.rule=Host(`notifications.${KOMUNITIN_DOMAIN}`)"
      - "traefik.http.routers.notifications-ts-${COMPOSE_PROJECT_NAME}.entrypoints=websec"
      - "traefik.http.routers.notifications-ts-${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.notifications-ts-${COMPOSE_PROJECT_NAME}.tls.certresolver=myresolver"
    
    networks:
      - proxy
  
  accounting:
    ports: !reset []
    expose:
      - "2025"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.accounting-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=2025"
      - "traefik.http.routers.accounting-${COMPOSE_PROJECT_NAME}.rule=Host(`accounting.${KOMUNITIN_DOMAIN}`)"
      - "traefik.http.routers.accounting-${COMPOSE_PROJECT_NAME}.entrypoints=websec"
      - "traefik.http.routers.accounting-${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.accounting-${COMPOSE_PROJECT_NAME}.tls.certresolver=myresolver"
    networks:
      - proxy
  
  integralces:
    ports: !reset []
    expose:
      - "2029"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.integralces-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=2029"
      - "traefik.http.routers.integralces-${COMPOSE_PROJECT_NAME}.rule=Host(`integralces.${KOMUNITIN_DOMAIN}`)"
      - "traefik.http.routers.integralces-${COMPOSE_PROJECT_NAME}.entrypoints=websec"
      - "traefik.http.routers.integralces-${COMPOSE_PROJECT_NAME}.tls=true"
      - "traefik.http.routers.integralces-${COMPOSE_PROJECT_NAME}.tls.certresolver=myresolver"
    networks:
      - proxy

  db-notifications:
    ports: !reset []
    networks:
      - proxy

  db-integralces:
    ports: !reset []
    networks:
      - proxy
  
  db-accounting:
    ports: !reset []
    networks:
      - proxy
  
  db-notifications-ts:
    ports: !reset []
    networks:
      - proxy
  
networks:
  proxy:
    name: ${KOMUNITIN_DOMAIN}
    external: true
