services:
  app:
    build:
      target: komunitin-app-build
    command: npm run dev  
    ports:
      - "2030:2030"
    volumes:
    # Can't use the whole app folder because it contains node_modules and dist and
    # since the volume is mounted after the image is built, the node_modules and dist
    # folders are then not available in the container. If you need to change any of
    # the files not included, you can rebuild the image or add the file to the volumes.
      - ./app/public:/app/public
      - ./app/src:/app/src
      - ./app/src-pwa:/app/src-pwa
      - ./app/test:/app/test
      - ./app/.env:/app/.env
      - ./app/package.json:/app/package.json
      - ./app/package-lock.json:/app/package-lock.json

    environment:
      MOCK_ENABLE: ${KOMUNITIN_APP_MOCK}
      MOCK_ENVIRONMENT: development
      MOCK_AUTH: ${KOMUNITIN_APP_MOCK}
      MOCK_ACCOUNTING: ${KOMUNITIN_APP_MOCK}
      MOCK_SOCIAL: ${KOMUNITIN_APP_MOCK}
      MOCK_NOTIFICATIONS: ${KOMUNITIN_APP_MOCK}
  notifications:
    build: 
      target: notifications-dev
    ports:
      - "2028:2028"
      - "40000:40000"
    volumes:
      - ./notifications:/opt/notifications


  cc:
    build:
      context: ./cc
    ports:
      - "8080:80"

  accounting:
    command: pnpm dev
    ports:
      - "2025:2025"
      - "9229:9229"
    volumes:
      - ./accounting/cli:/app/cli
      - ./accounting/openapi:/app/openapi
      - ./accounting/prisma:/app/prisma
      - ./accounting/src:/app/src
      - ./accounting/test:/app/test
      - ./accounting/.env:/app/.env
      - ./accounting/package.json:/app/package.json
      - ./accounting/pnpm-lock.yaml:/app/pnpm-lock.yaml


  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db-integralces
    environment:
      PMA_HOSTS: "db-integralces,db-accounting"
      PMA_PORTS: "3306,5432"
    ports:
      - "2026:80"
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
     - REDIS_HOSTS=local:redis:6379
    ports:
     - "2027:8081" 
  