services:
  app:
    ports: !reset []
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.app.loadbalancer.server.port=80"
      - "traefik.http.routers.app.rule=Host(`${KOMUNITIN_DOMAIN}`)"
      - "traefik.http.routers.app.entrypoints=websec"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
    networks:
      - proxy
  
  notifications:
    ports: !reset []
    expose:
      - "2028"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.notifications.loadbalancer.server.port=2028"
      - "traefik.http.routers.notifications.rule=Host(`notifications.${KOMUNITIN_DOMAIN}`)"
      - "traefik.http.routers.notifications.entrypoints=websec"
      - "traefik.http.routers.notifications.tls=true"
      - "traefik.http.routers.notifications.tls.certresolver=myresolver"
    networks:
      - proxy
  
  accounting:
    ports: !reset []
    expose:
      - "2025"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.accounting.loadbalancer.server.port=2025"
      - "traefik.http.routers.accounting.rule=Host(`accounting.${KOMUNITIN_DOMAIN}`)"
      - "traefik.http.routers.accounting.entrypoints=websec"
      - "traefik.http.routers.accounting.tls=true"
      - "traefik.http.routers.accounting.tls.certresolver=myresolver"
    networks:
      - proxy
  
  integralces:
    ports: !reset []
    expose:
      - "2029"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.integralces.loadbalancer.server.port=2029"
      - "traefik.http.routers.integralces.rule=Host(`integralces.${KOMUNITIN_DOMAIN}`)"
      - "traefik.http.routers.integralces.entrypoints=websec"
      - "traefik.http.routers.integralces.tls=true"
      - "traefik.http.routers.integralces.tls.certresolver=myresolver"
    networks:
      - proxy

  redis:
    networks:
      - proxy

  db-integralces:
    networks:
      - proxy
  
  db-accounting:
    networks:
      - proxy

networks:
  proxy:
    name: ${KOMUNITIN_DOMAIN}
    external: true
