services:
  app:
    ports: []
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`${KOMUNITIN_DOMAIN}`)"
      - "traefik.http.routers.app.entrypoints=websec"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
  
  notifications:
    ports: []
    expose:
      - "2028"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notifications.rule=Host(`notifications.${KOMUNITIN_DOMAIN}`)"
      - "traefik.http.routers.notifications.entrypoints=websec"
      - "traefik.http.routers.notifications.tls=true"
      - "traefik.http.routers.notifications.tls.certresolver=myresolver"
  
  accounting:
    ports: []
    expose:
      - "2025"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.accounting.rule=Host(`accounting.${KOMUNITIN_DOMAIN}`)"
      - "traefik.http.routers.accounting.entrypoints=websec"
      - "traefik.http.routers.accounting.tls=true"
      - "traefik.http.routers.accounting.tls.certresolver=myresolver"
  
  integralces:
    ports: []
    expose:
      - "2029"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.integralces.rule=Host(`integralces.${KOMUNITIN_DOMAIN}`)"
      - "traefik.http.routers.integralces.entrypoints=websec"
      - "traefik.http.routers.integralces.tls=true"
      - "traefik.http.routers.integralces.tls.certresolver=myresolver"

networks:
  default:
    name: ${KOMUNITIN_DOMAIN}
    external: true
