services:
  db:
    build:
      context: ./docker/db
    container_name: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_APP_USER: accounting
      POSTGRES_APP_PASSWORD: accounting
  stellar:
    image: stellar/quickstart
    container_name: stellar
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      NETWORK: local
  cc:
    build:
      context: ./cc
    container_name: cc
    restart: unless-stopped
    ports:
      - "8080:80"
    extra_hosts:
      - "twig.cc-server:127.0.0.1"
      - "branch.cc-server:127.0.0.1"
      - "trunk.cc-server:127.0.0.1"
      - "branch2.cc-server:127.0.0.1"
  accounting:
    build:
      context: .
    ports:
      - "2025:2025"
      - "9229:9229"
    volumes:
      - ./cli:/app/cli
      - ./openapi:/app/openapi
      - ./prisma:/app/prisma
      - ./src:/app/src
      - ./test:/app/test
      - ./.env:/app/.env
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
    depends_on:
      - db
      - stellar
      - cc
    container_name: accounting
    restart: unless-stopped
    environment:
      POSTGRES_APP_USER: "accounting"
      POSTGRES_APP_PASSWORD: "accounting"
      DATABASE_URL: "postgresql://accounting:accounting@db:5432/accounting?schema=public"
      MASTER_PASSWORD: "Test App Password"
      MASTER_PASSWORD_SALT: "Test master password salt"
      STELLAR_CHANNEL_ACCOUNTS_ENABLED: "false"
      STELLAR_NETWORK: "local"
      STELLAR_HORIZON_URL: "http://stellar:8000"
      STELLAR_FRIENDBOT_URL: "http://stellar:8000/friendbot"
      AUTH_JWKS_URL: "http://integralces2029/.well-known/jwks.json"
      AUTH_JWT_ISSUER: "http://localhost:2029/"
      AUTH_JWT_AUDIENCE: "komunitin-app,komunitin-notifications"
      NOTIFICATIONS_API_URL: "http://notifications:2028"
      API_BASE_URL: "http://localhost:2025"
      NOTIFICATIONS_API_USERNAME: "komunitin"
      NOTIFICATIONS_API_PASSWORD: "komunitin"
      DOCKER: true
      NODE_ENV: "development"
    extra_hosts:
      - "host.docker.internal:host-gateway"
