services:
  db-social:
    build:
      context: ../shared/docker/db
      args:
        INSTALL_POSTGIS: "true"
        INSTALL_PGVECTOR: "true"
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_APP_USER: social
      POSTGRES_APP_PASSWORD: social
      POSTGRES_APP_EXTENSIONS: postgis,vector,pg_trgm,btree_gin,unaccent
      # # Backup configuration
      # WALG_ENABLE: ${DB_BACKUP_ENABLE:-true}
      # WALG_S3_PREFIX: ${S3_PREFIX}/db-social
      # WALG_COMPRESSION_METHOD: zstd
      # AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY}
      # AWS_SECRET_ACCESS_KEY: ${S3_SECRET_KEY}
      # AWS_ENDPOINT: ${S3_ENDPOINT}
      # AWS_REGION: ${S3_REGION:-us-east-1}
      # AWS_S3_FORCE_PATH_STYLE: ${S3_FORCE_PATH_STYLE:-false}
    volumes:
      - db-social:/var/lib/postgresql/data

volumes:
  db-social: