name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build . --file Dockerfile --tag komunitin-app:$(date +%s)
    
    - name: Run
      run: docker run -d -p 80:80 komunitin-app --rm
      
    - name: Test
      run: wget http://localhost/ 
